### ISSUE TITLE
Syntax error and function

### ISSUE THREAD

**Issue by brshark-zz** [IvanGlinkin/Fast-Google-Dorks-Scan#1]
Hi Ivan, i received some errors when trying to run this script. 
Example for usage: "sh FGDS.sh domain.com" , Please, can you tell me if I need to do it differently? thanks

Some of:
FGDS.sh: 36: Syntax error: "(" unexpected
FGDS.sh: 57: Syntax error: "(" unexpected
FGDS.sh: 67: Syntax error: "(" unexpected
FGDS.sh: 90: function: not found
FGDS.sh: 97: [: unexpected operator
FGDS.sh: 119: Syntax error: "(" unexpected (expecting "fi")

**Comment by jakuta-tech** [comment]
It should be set as executable so just

`./FGDS.sh domain.com`

alternatively, start it with bash direct

`bash FGDS.sh domain.com`

**Comment by IvanGlinkin** [comment]
I think there was some kind of mistake while downloading or copying the source code. 
Try this tutorial - https://www.ethicalhackx.com/best-google-dorks-scanner/
