### ISSUE TITLE
$'\r': command not found

### ISSUE THREAD

**Issue by DamianMorozov** [IvanGlinkin/Fast-Google-Dorks-Scan#4]
I try to use it on my Windows machine under WSL Ubuntu:
```
bash ./FGDS.sh megacorp.one
```
Have this result:
```
./FGDS.sh: line 6: $'\r': command not found
./FGDS.sh: line 16: $'\r': command not found
./FGDS.sh: line 37: $'\r': command not found
./FGDS.sh: line 58: $'\r': command not found
./FGDS.sh: line 68: $'\r': command not found

#########################################################
#                                                       #
#                Fast Google Dorks Scan                 #
#                                                       #
#########################################################

# https://www.linkedin.com/in/IvanGlinkin/ | @IvanGlinkin
# Version:                  1.010
./FGDS.sh: line 78: $'\r': command not found
./FGDS.sh: line 90: syntax error near unexpected token `$'{\r''
'/FGDS.sh: line 90: `function Query {
```

**Comment by IvanGlinkin** [comment]
Hi,
Do you have such kind of problem on the clear Ubuntu itself?
It has not been tested under the WSL so currently I can tell you nothing regarding that issue.
Moreover, if you see at the source code, there is no any \r command. But, according to the article -> https://askubuntu.com/questions/1148263/r-added-end-of-the-script-command, `the \r issue suggests you have edited the script file on a Windows machine. Windows uses \r\n as the [line terminator](https://en.wikipedia.org/wiki/Newline) while Linux (and most other operating systems) use \n alone. When you edit a file in Windows, Windows will add \r to the end of the lines and that will break your scripts.`
Try to redownload the script or use the suggestions from the article above.
Regards,
Ivan

**Comment by DamianMorozov** [comment]
It is not help. All lines have CRLF (\r\n) at the end.
I have to try remove empty lines,  it's help to remove part of error strings. But I still have one error at teh string `function Query {`.

**Comment by Asingh961** [comment]
I am beginner and I am using termux, can I hack Instagram password through  termux, plzz reply

**Comment by IvanGlinkin** [comment]
@Asingh961 Are you kidding me? First of all, it's totally illegal and I won't support you in any activities regarding that. Then, you are writing that publicly. Aren't you scared to be chasing by the law enforcement and the Instagram owner?

**Comment by Asingh961** [comment]
Sorry, I am professional so 🥺

**Comment by Asingh961** [comment]
Sorry, I am not professional so 🥺
